version: '3.8'
services:
  api:
    build: ./backend
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - API_DEBUG=${API_DEBUG}
    restart: always
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
          - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - api
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    restart: always

